name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build Docker Image
      run: |
        docker build -t emrodriguezx/docker-graphql:0.0.3 .
        docker image tag emrodriguezx/docker-graphql:0.0.3 emrodriguezx/docker-graphql
    - name: Push Docker Image
      run: |
        docker push emrodriguezx/docker-graphql:0.0.3
        docker push emrodriguezx/docker-graphql:latest
    
    
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
